// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-12-27 13:33:06.107809 +0800 CST m=+0.045196949

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {},
        "/api": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "API Handler",
                "parameters": [
                    {
                        "description": "a api body",
                        "name": "resbody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/defs.APIBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "userhome.html",
                        "schema": {
                            "type": "html"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload/{vid-id}": {
            "get": {
                "summary": "Proxy Handler"
            },
            "post": {
                "summary": "Proxy Handler"
            }
        },
        "/userhome": {}
    },
    "definitions": {
        "defs.APIBody": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "req_body": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
